services:
  budget-planner-app-dev:
    image: postgres:15
    container_name: budget-planner-app-dev
    restart: always
    env_file:
      - './common/.env'
    volumes:
      - ./data/budget-planner:/var/lib/postgresql/data
    ports:
      - '4444:5432'
