services:
  budget-planner-app-dev:
    image: postgres:15
    container_name: budget-planner-app-dev
    restart: always
    env_file:
      - './common/.env'
    volumes:
      - ./data/budget-planner:/var/lib/postgresql/data
    ports:
      - '4444:5432'

  authentication-service:
    build:
      context: .
      dockerfile: ./services/authentication-service/Dockerfile
    container_name: authentication-service
    ports:
      - '3001:3000'
    env_file:
      - ./services/authentication-service/.env
    depends_on:
      - budget-planner-app-dev

  budget-service:
    build:
      context: .
      dockerfile: ./services/budget-service/Dockerfile
    container_name: budget-service
    ports:
      - '3002:3000'
    env_file:
      - ./services/budget-service/.env
    depends_on:
      - budget-planner-app-dev

  expense-service:
    build:
      context: .
      dockerfile: ./services/expense-service/Dockerfile
    container_name: expense-service
    ports:
      - '3003:3000'
    env_file:
      - ./services/expense-service/.env
    depends_on:
      - budget-planner-app-dev

  report-service:
    build:
      context: .
      dockerfile: ./services/report-service/Dockerfile
    container_name: report-service
    ports:
      - '3004:3000'
    env_file:
      - ./services/report-service/.env
    depends_on:
      - budget-planner-app-dev

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    ports:
      - '3005:3000'
    env_file:
      - ./services/user-service/.env
    depends_on:
      - budget-planner-app-dev